version: "3.2"

volumes:
 productdata:
 

networks:
 frontend:
 backend:

services:

 app:
  build: 
   context: .
   dockerfile: Dockerfile
  networks:
   - backend
   - frontend
  environment:
    MYSQL_SERVER_NAME=127.0.0.1
  depends_on:
   - mysql  
  ports:
   - 5000:80
  env_file:
   - configuration.env 

 mysql:
  image: "mysql:8.0.0"
  volumes:
   - productdata:/var/lib/mysql
   - /db:/docker-entrypoint-initdb.d/
  networks:
   - backend
  env_file:
   - configuration.env
  environment:
   - MYSQL_ROOT_PASSWORD = 105481Do
   - MYSQL_DATABASE=users
   - MYSQL_USER=root
   - MYSQL_PASSWORD=105481Do

    