version: "3.2"

volumes:
 productdata:

networks:
 frontend:
 backend:

services:

 app:
  build: 
   context: .
   dockerfile: Dockerfile
  networks:
   - backend
   - frontend
  environment:
   - DBHOST = mysql
   - DBPORT = 3306
   - DBPASSWORD = 105481Do
   - DBUSER = root
  depends_on:
   - mysql  
  ports:
   - 5000:80 

 mysql:
  image: "mysql:8.0.0"
  volumes:
   - productdata:/var/lib/mysql
  networks:
   - backend
  env_file:
   - configuration.env
  environment:
   - MYSQL_ROOT_PASSWORD = 105481Do
   - bind-address = 0.0.0.0
   - MYSQL_USER = root
   - MYSQL_DATABASE = userDb 

    