version: "3.2"

volumes:
 data:

services:

 mysqlDb:
  image: "mysql:8.0.0"
  restart: always
  volumes:
    - data:/var/lib/mysql
    - /script:/docker-entrypoint-initdb.d
  ports:
    - "3306:3306"
  environment:
      MYSQL_ROOT_PASSWORD: 105481Do
      MYSQL_DATABASE: iot
      MYSQL_USER: root 
 app:
  build: 
   context: .
   dockerfile: Dockerfile 
  ports:
   - "80:80"
  links: 
   - mysqlDb

  

