version: "3.2"

volumes:
 productdata:
 
services:

 app:
  build: 
   context: .
   dockerfile: Dockerfile
  environment:
    MYSQL_SERVER_NAME : "127.0.0.1"
  depends_on:
   - mysql  
  links:
   - mysql
  ports:
   - "5000:80"
  env_file:
   - configuration.env 

 mysql:
  image: "mysql:8.0.0"
  ports:
    - "3306:3306"
  volumes:
   - productdata:/var/lib/mysql
  env_file:
      MYSQL_ROOT_PASSWORD: "105481Do"
      MYSQL_DATABASE: "users"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "105481Do"



    