version:"3"

volumes:
 productdata:

networks:
 frontend:
 backend:

services:

 mysql:
  image:"mysql:8.0.0"
  volumes:
   - productdata:/var/lib/mysql
  networks:
   - backend
  environment:
   - MYSQL_ROOT_PASSWORD = 105481Do
   - bind-address = 0.0.0.0

    