version: "3.2"

volumes:
 productdata:

networks:
 frontend:
 backend:

services:

 app:
  build: 
   context: .
   dockerfile: Dockerfile
  networks:
   - backend
   - frontend
  environment:
    MYSQL_SERVER_NAME: ${MYSQL_SERVER_NAME}
  depends_on:
   - mysql  
  ports:
   - 5000:80
  env_file:
   - secrets.env 

 mysql:
  image: "mysql:8.0.0"
  volumes:
   - productdata:/var/lib/mysql
  networks:
   - backend
  env_file:
   - configuration.env
  environment:
   MYSQL_RANDOM_ROOT_PASSWORD: !!str yes

    