version: "3.2"
 
services:

 app:
  build: 
   context: .
   dockerfile: Dockerfile
  depends_on:
   - mysqlDb  
  ports:
   - "5000:80"

 mysqlDb:
  image: "mysql:8.0.3"
  ports:
    - "3308:3306"
  environment:
      MYSQL_ROOT_PASSWORD: 105481Do
      MYSQL_DATABASE: iot

    